### PR TITLE
fix: searchbar focus on `Esc` key press

### PR DESCRIPTION
**Pull request by shanpriyan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What changes did you make? (Give an overview)

Fixed search bar focusing on pressing Esc

#### Related Issues

SImilar to https://github.com/eslint/eslint/issues/16699 (for Blog page)

### CODE REVIEW

**Review by kecrily — APPROVED** [review]
LGTM, I will merge this PR immediately after the merge at https://github.com/eslint/eslint/pull/16700

**Review by harish-sethuraman — APPROVED** [review]
LGTM, Thanks

**Comment by harish-sethuraman** [comment]
Can you fix the lint please? @shanpriyan

**Comment by shanpriyan** [comment]
> Can you fix the lint please? @shanpriyan

the CI failed during `build` 
image
Not sure why it's happening, I'm able to build successfully in my local environment

**Comment by harish-sethuraman** [comment]
Yea I guess it should be fixed after https://github.com/eslint/eslint.org/pull/392

**Review by amareshsm — COMMENTED** [review]
https://github.com/eslint/eslint/issues/16699 As mentioned in the issue it doesn't lose focus when we press ESC within the search box. 🤔

**Comment by shanpriyan** [comment]
> [eslint/eslint#16699](https://github.com/eslint/eslint/issues/16699) As mentioned in the issue it doesn't lose focus when we press ESC within the search box. thinking

Shall I add that too? 🤔

**Comment by shanpriyan** [comment]
@amareshsm

https://github.com/eslint/eslint.org/pull/393/commits/1a281cea029d7abf83a35b2af749d464a3265bd5 - Addresses the second point in the issue

**Comment by shanpriyan** [comment]
After https://github.com/eslint/eslint.org/commit/1a281cea029d7abf83a35b2af749d464a3265bd5

[eslint-esc.webm](https://user-images.githubusercontent.com/42532987/209445288-20c616d6-2153-48b7-ab78-01bdd1cd74f8.webm)

**Comment by amareshsm** [comment]
> > [eslint/eslint#16699](https://github.com/eslint/eslint/issues/16699) As mentioned in the issue it doesn't lose focus when we press ESC within the search box. thinking
> 
> Shall I add that too? 🤔

ya, we can I checked a few sites they have implemented.

 https://vercel.com/docs
 https://developer.mozilla.org/en-US/

**Comment by shanpriyan** [comment]
Since https://github.com/eslint/eslint/pull/16700 had been merged already

Should I send a new PR with this change https://github.com/eslint/eslint.org/commit/1a281cea029d7abf83a35b2af749d464a3265bd5 for eslint.org/docs search bar ?

**Review by snitin315 — COMMENTED** [review]
Lint job is failing.

**Review by amareshsm — APPROVED** [review]
LGTM

**Comment by shanpriyan** [comment]
> Lint job is failing.

https://github.com/eslint/eslint.org/pull/393#issuecomment-1364552255```

**Pull request merged**
