### PR TITLE
fix: Show ads on all pages

### LINKED ISSUE #520: Bug: Ad only showing on the homepage
### URL(s)

https://eslint.org
https://eslint.org/blog

### What did you do?

When to the homepage and then the blog page

### What did you expect to happen?

The ad shows up in the upper-right on both pages.

### What actually happened?

The ad shows up only on the homepage and is missing from all other pages (blog posts, team, etc.)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What changes did you make? (Give an overview)

Added `with context` when importing the hero macro. That allows `ad.html` to access global data.

#### Related Issues

fixes #520

### CODE REVIEW

**Review by amareshsm — APPROVED** [review]
LGTM, This fix looks simple.

**Review by amareshsm — CHANGES_REQUESTED** [review]
Need to update in 'components.html' also.

https://github.com/eslint/eslint.org/blob/41fb3f731454e34b4fa291f2c409bcc26b2a3a63/src/_includes/layouts/components.html#L8

**Comment by nzakas** [comment]
Good catch!

**Review by amareshsm — APPROVED** [review]
LGTM 🎉

**Pull request merged**
