### PR TITLE
feat: [playground] Add revert configs to default option

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What changes did you make? (Give an overview)

A "Reset" button has been added to restore the config to the default ESLint settings, matching what users see when they first open the playground.

image

#### Related Issues
#592 

#### Is there anything you'd like reviewers to focus on?
The button is currently labelled "Revert Configs to Default," but I'm open to suggestions for a different name also.

### CODE REVIEW

**Comment by nzakas** [comment]
How about just "Reset"?

**Comment by nzakas** [comment]
Just to be clear, the button is resetting the config to what it was when the page was loaded correct? (So that it's either being read from localStorage or is the default for the playground?)

**Comment by harish-sethuraman** [comment]
> Personally, I support this proposal 👍 I've often been the guy who was looking for that button, only to realize it wasn't there every time again. Even so, I'm aware of recommendations not to use reset buttons in forms for various reasons like [this one](https://ux.stackexchange.com/a/93688/36182), or [this one](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset) from MDN (in the note), so I'd be interested in other opinions.


we had some discussions related to naming the button reset @nzakas thats why we named it different.

**Comment by amareshsm** [comment]
> Just to be clear, the button is resetting the config to what it was when the page was loaded correct? (So that it's either being read from localStorage or is the default for the playground?)

The button resets the config to the default ESLint configuration, which is the same as what users see when they first open the playground.

**Comment by nzakas** [comment]
Then I definitely think "Reset" is a clearer title for the button.

**Comment by amareshsm** [comment]
> Then I definitely think "Reset" is a clearer title for the button.

👍   I’ve updated the button name.

**Comment by nzakas** [comment]
It's working for me. I'm not sure what you did in the video, but you need to add or remove some rules and then hit Reset to see it work.

**Comment by harish-sethuraman** [comment]
Seems to be working fine. I was wondering if it would reset the playground's config to empty state.

**Review by harish-sethuraman — APPROVED** [review]
LGTM

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
