### PR TITLE
feat: generate open graph image in netlify edge function

### PR DESCRIPTION
**Pull request by kecrily**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Generates an open graph image. Improve the experience of previewing documents in social media.

#### What changes did you make? (Give an overview)

It consists of six parameters.

https://github.com/eslint/eslint.org/blob/9a7793b41a1ba953b9bba4799853246e29975c14/functions/og.tsx#L30-L36

`/og?title=Core%20Concepts&summary=A%20pluggable%20and%20configurable%20linter%20tool%20for%20identifying%20and%20reporting%20on%20patterns%20in%20JavaScript.%20Maintain%20your%20code%20quality%20with%20ease.%20&is_rule=false&recommended=&fixable=&suggestions=`

image

`/og?title=no-div-regex&summary=A%20pluggable%20and%20configurable%20linter%20tool%20for%20identifying%20and%20reporting%20on%20patterns%20in%20JavaScript.%20Maintain%20your%20code%20quality%20with%20ease.%20&is_rule=true&recommended=false&fixable=code&suggestions=
`
image

#### Related Issues

Close https://github.com/eslint/eslint.org/issues/362

#### Is there anything you'd like reviewers to focus on?

It can be abused, although that doesn't mean much.

### CODE REVIEW

**Review by nzakas — APPROVED** [review]
This looks amazing, thank you! Would like another review before merging.

**Review by amareshsm — APPROVED** [review]
Nice!  🎉 
LGTM

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Comment by harish-sethuraman** [comment]
A small suggestion would be to configure ellipsis at the end so that it doesn't overflow when there is large number of text? Other things LGTM. Great work 🎉 

preview

**Pull request merged**
