### PR TITLE
chore: Add Powered by Algolia label to the search

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Add Powered by Algolia label to the search

#### What changes did you make? (Give an overview)
Added powered by Algolia label under the search box
image

image

#### Related Issues
https://github.com/eslint/eslint/issues/18620

#### Is there anything you'd like reviewers to focus on?
Need to verify that the changes work correctly across all device screen sizes.

### CODE REVIEW

**Comment by nzakas** [comment]
Screenshot 2024-06-28 at 17-05-19 News and Updates - ESLint - Pluggable JavaScript Linter

Feedback:

1. The color of the Algolia logo and text looks pretty bad in both light and dark themes. Can we just have it be the same color as the "Powered by"?
2. The baseline of the word "Algolia" is slightly higher than "Powered by", making it look broken. Can we get that baseline to match?

**Comment by nzakas** [comment]
@amareshsm are you still working on this? If not, I can take it over. We'd like to get this updated and published ASAP.

**Comment by amareshsm** [comment]
> Screenshot 2024-06-28 at 17-05-19 News and Updates - ESLint - Pluggable JavaScript Linter
> 
> Feedback:
> 
> 1. The color of the Algolia logo and text looks pretty bad in both light and dark themes. Can we just have it be the same color as the "Powered by"?
> 2. The baseline of the word "Algolia" is slightly higher than "Powered by", making it look broken. Can we get that baseline to match?

changes done. I have updated the description with the latest screenshots.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
