### PR TITLE
fix: Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')

### PR DESCRIPTION
**Pull request by Tanujkanti4441**
TypeError on the playground page is fixed. for #298

### CODE REVIEW

**Comment by snitin315** [comment]
@Tanujkanti4441 can you accept CLA?

**Comment by Tanujkanti4441** [comment]
I have @snitin315 sir

**Review by harish-sethuraman — APPROVED** [review]
Thanks! 

LGTM

**Review by kecrily — APPROVED** [review]
LGTM

**Review by snitin315 — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
