### PR TITLE
docs: fix typo in blog post

### PR DESCRIPTION
**Pull request by DamianGlowala**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amareshsm** [comment]
@DamianGlowala Pls sign the [Contributor License Agreement (CLA)](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/19114526/421537080/599/#/?version=2)

https://eslint.org/docs/latest/contribute/#sign-the-cla

**Comment by nzakas** [comment]
@DamianGlowala last chance. We just need you to sign the CLA before we can merge this. Thanks!

**Comment by DamianGlowala** [comment]
Happy for either of you to submit a PR instead with signed CLA.

**Comment by amareshsm** [comment]
> DamianGlowala

https://github.com/eslint/eslint.org/pull/604 done. Thanks.

**Pull request closed without merging**
