### PR TITLE
feat: Schedule blog post

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Schedule @captbaritone's blog post for next Tuesday.

#### Is there anything you'd like reviewers to focus on?

It should be safe to merge this ahead of time because we don't render future posts in production.

### CODE REVIEW

**Comment by captbaritone** [comment]
Post looks good to me! One thing I noticed is that even though I have an author bio defined in the repo (from my previous post) I don't see it used anywhere in this post. Is that expected?

**Comment by mdjermanovic** [comment]
> It should be safe to merge this ahead of time because we don't render future posts in production.

I tested this locally with `CONTEXT=production` environment variable, and:

1. The page is rendered and can be opened directly.
2. It doesn't appear in the list of blog posts on https://eslint.org/blog/, but it does appear in the list of blog posts on https://eslint.org/blog/category/case-studies/.
3. It appears in `sitemap.xml`.

Maybe we should fix this before merging?

**Comment by mdjermanovic** [comment]
> One thing I noticed is that even though I have an author bio defined in the repo (from my previous post) I don't see it used anywhere in this post. Is that expected?

Author bio is at the end of the blog post:

https://deploy-preview-645--new-eslint.netlify.app/blog/2024/10/code-review-nit-to-ecosystem-improvements/#conclusion

image

**Comment by nzakas** [comment]
Now that https://github.com/eslint/eslint.org/pull/646 is merged, I think it should be safe to merge this?

We do a nightly data fetch to regenerate the site, so I think this will get automatically published on Tuesday.

**Comment by mdjermanovic** [comment]
> Now that #646 is merged, I think it should be safe to merge this?

Yes, I'll merge it now and check the build log and the site.

> We do a nightly data fetch to regenerate the site, so I think this will get automatically published on Tuesday.

It should be as there's always some change in the data. I'll doublecheck on Tuesday.

**Review by mdjermanovic — APPROVED** [review]

**Comment by mdjermanovic** [comment]
Works fine:

```
5:25:12 PM: > npx @11ty/eleventy
5:25:13 PM: Ignoring future blog post src/content/blog/2024-10-08-code-review-nit-to-ecosystem-improvements.md
5:25:16 PM: [11ty] Writing _site/feed.xml from ./src/static/feed.njk
...
```

And https://eslint.org/blog/2024/10/code-review-nit-to-ecosystem-improvements/ doesn't exist yet.

**Comment by mdjermanovic** [comment]
The blog post is published now:

https://eslint.org/blog/

https://eslint.org/blog/2024/10/code-review-nit-to-ecosystem-improvements/

**Pull request merged**
