### PR TITLE
fix: style issues in no-js mode

### PR DESCRIPTION
**Pull request by Tanujkanti4441**
<!--
    Thank you for contributing!

    ESLint adheres to the [JS Foundation Code of Conduct](https://eslint.org/conduct).
-->

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?
There are some styles that are different in no-js mode as compared enabled javascript mode.
<!--
    Please ensure your pull request is ready:

    - Read the pull request guide (https://eslint.org/docs/latest/contribute/pull-requests)
    - Update documentation for this change (if appropriate)
-->

<!--
    The following is required for all pull requests:
-->

#### What changes did you make? (Give an overview)
This PR fixes following style in no-js mode.


| JavaScript Enabled                                                                                                                                                                                                              | JavaScript Disabled                                                                                                                                                                                                                       |
| ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <img src="https://github.com/user-attachments/assets/420099a6-8da2-46b9-bbb8-9914803fd09e"> | <img src="https://github.com/user-attachments/assets/335b3c0f-56ee-41a1-ba80-455374b5537c"> | 
<img src="https://github.com/user-attachments/assets/ed2cb53f-2ba2-499e-934c-ca4e130e45fc"> | <img src="https://github.com/user-attachments/assets/0b17149d-9293-488e-bbef-647640ce332d"> | 
<img src="https://github.com/user-attachments/assets/be0c0ae5-d15d-42ab-9f90-9d8b001d7f7c"> | <img src="https://github.com/user-attachments/assets/8526b75c-0d88-4876-a4c4-d944232dc1d8"> |
<img src="https://github.com/user-attachments/assets/c4d57f7d-7b27-467a-8872-56fe992832e9"> | <img src="https://github.com/user-attachments/assets/23fb570c-cdb1-4bdb-b139-77ae22e799b9"> |


#### Related Issues

#### Is there anything you'd like reviewers to focus on?

<!-- markdownlint-disable-file MD004 -->

### CODE REVIEW

**Review by amareshsm — COMMENTED** [review]
Please fix the lint issue; Prettier is failing.

**Comment by amareshsm** [comment]
On the donation page, the GitHub company logo is not visible in the "Ways to Sponsor" section when using dark theme in no-JS mode.

image

**Review by amareshsm — COMMENTED** [review]
In the light theme ESLint logo is not visible

image

**Comment by Tanujkanti4441** [comment]
> In the light theme ESLint logo is not visible

I could not reproduce this, can you please share is it in js or no-js mode, or any steps to reproduce?

**Comment by amareshsm** [comment]
> > In the light theme ESLint logo is not visible
> 
> I could not reproduce this, can you please share if it is in js or no-js mode, or any steps to reproduce?

I can reproduce this issue locally. you can check this preview [link](https://deploy-preview-628--new-eslint.netlify.app/) in the no-js mode light theme the ESlint logo is not visible.

**Review by amareshsm — COMMENTED** [review]
@Tanujkanti4441  Hey can you this pr once I checked it looks like all of the issues are fixed.

**Comment by Tanujkanti4441** [comment]
> @Tanujkanti4441  Hey can you this pr once I checked it looks like all of the issues are fixed. 

We still have font-weight related issues as https://github.com/eslint/eslint/pull/18916 PR

**Comment by Tanujkanti4441** [comment]
> Screenshot 2024-11-13 at 10 50 21 PM
> I can see this isn't working? 🤔 IG this is powered by css / scripts from the other repo? so its fine? 
> 

I think it's the getting started page of docs and this is not the part of eslint.org repo that is already fixed in https://github.com/eslint/eslint/pull/18916 PR.

**Review by harish-sethuraman — APPROVED** [review]
LGTM. Thanks for working on this PR.

**Review by amareshsm — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
