### PR TITLE
fix: footer social icons layout with nowrap

### PR DESCRIPTION
**Pull request by shanpriyan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Fixed footer socials icon with nowrap

#### What changes did you make? (Give an overview)

<details>
<summary>Homepage</summary>

image
image
</details>

<details>
<summary>Playground</summary>

image
image
</details>

#### Related Issues 

Ref https://github.com/eslint/eslint.org/pull/381#issuecomment-1349514328

### CODE REVIEW

**Review by kecrily — APPROVED** [review]
LGTM, but need someone else to check again

**Comment by harish-sethuraman** [comment]
Hey I guess https://github.com/eslint/eslint.org/pull/382 PR is also solving the same issue already. Please refrain from raising another PR while someone else is working on the same 😕. @amareshsm would you like to see if this works?

**Comment by shanpriyan** [comment]
> Hey I guess #382 PR is also solving the same issue already. Please refrain from raising another PR while someone else is working on the same confused. @amareshsm would you like to see if this works?

Hey, #382 PR wraps the icons to next line. This PR prevents the icon from wrapping and is a follow-up of https://github.com/eslint/eslint.org/pull/382#discussion_r1050150928

**Comment by amareshsm** [comment]
> > Hey I guess #382 PR is also solving the same issue already. Please refrain from raising another PR while someone else is working on the same 😕. @amareshsm would you like to see if this works?
> 
> Hey, #382 PR wraps the icons to next line. This PR prevents the icon from wrapping and is a follow-up of [#382 (comment)](https://github.com/eslint/eslint.org/pull/382#discussion_r1050150928)

Ya, #382 wraps the icons. But both PRs solve the same layout issue. Initially, we decided to [wrap the icons](https://github.com/eslint/eslint.org/pull/381#issuecomment-1351990260). So I sent a PR.

**Review by amareshsm — APPROVED** [review]
LGTM. Leaving this for others' opinion. If we are fine with this approach we can close https://github.com/eslint/eslint.org/pull/382.

**Review by harish-sethuraman — APPROVED** [review]
LGTM. Thank you

**Comment by harish-sethuraman** [comment]
@amareshsm  lets do the same in the main eslint/eslint too 👍🏻

**Pull request merged**
