### PR TITLE
fix: missing characters while typing in code editor

### LINKED ISSUE #299: Bug: Missing few characters while typing in code editor (playground)
### URL(s)

https://eslint.org/play/

### What did you do?

Typed characters in a faster pace in code editor (playground)

### What did you expect to happen?

Should take all the entered characters

### What actually happened?

Skipped few characters

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

https://user-images.githubusercontent.com/42532987/183092112-974eedc2-c017-44e6-8385-511613b24618.mp4

### PR DESCRIPTION
**Pull request by shanpriyan**
- Added `debounce` in code editor with 400ms delay
 
Resolves #299

### CODE REVIEW

**Review by kecrily — APPROVED** [review]
Looks good to me

**Comment by harish-sethuraman** [comment]
Ideally I'd not suggest adding debounce to code editors. We first have to find out why there are misses and then fix them adding debounce doesn't seem like a good idea to me. :(

**Review by snitin315 — COMMENTED** [review]
I'm not able to reproduce it issue on macOS with firefox. What environment are you using?

**Comment by shanpriyan** [comment]
> I'm not able to reproduce it issue on macOS with firefox. What environment are you using?

Chrome on windows

**Comment by snitin315** [comment]
> Ideally I'd not suggest adding debounce to code editors. We first have to find out why there are missed and then fix them adding debounce doesn't seem like a good idea to me. :(

I suppose it's okay. The old playground seems to have a similar implementation

https://github.com/eslint/archive-website/blob/286f9a778f82bd6279d94f3f54857b388d905df9/src/js/demo/components/Editor.jsx#L8

https://github.com/eslint/archive-website/blob/286f9a778f82bd6279d94f3f54857b388d905df9/src/js/demo/components/Editor.jsx#L95

**Comment by snitin315** [comment]
>Chrome on windows

I'm able to reproduce on windows 👍🏻

**Review by snitin315 — APPROVED** [review]
LGTM, Thanks for contributing ⭐

**Comment by shanpriyan** [comment]
> > Ideally I'd not suggest adding debounce to code editors. We first have to find out why there are missed and then fix them adding debounce doesn't seem like a good idea to me. :(
> 
> I suppose it's okay. The old playground seems to have a similar implementation
> 
> https://github.com/eslint/archive-website/blob/286f9a778f82bd6279d94f3f54857b388d905df9/src/js/demo/components/Editor.jsx#L8
> 
> https://github.com/eslint/archive-website/blob/286f9a778f82bd6279d94f3f54857b388d905df9/src/js/demo/components/Editor.jsx#L95

Shall I change the delay to `500ms` like the old editor?

**Comment by snitin315** [comment]
`400ms` seems to be working fine 👍🏻

**Review by amareshsm — APPROVED** [review]

**Comment by amareshsm** [comment]
LGMT

**Review by harish-sethuraman — APPROVED** [review]
LGTM thanks

**Pull request merged**
