### PR TITLE
fix: Fixed infinite flicker

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What changes did you make? (Give an overview)
fixes https://github.com/eslint/eslint.org/issues/551
#### Related Issues
https://github.com/eslint/eslint.org/issues/551
#### Is there anything you'd like reviewers to focus on?

I have mostly checked all the existing functionalities, but need to verify again to ensure that this change does not impact them.

### CODE REVIEW

**Comment by nzakas** [comment]
Is this ready for review? We generally don't review drafts, so if you'd like feedback from the team, please click "Ready for Review"

**Comment by nzakas** [comment]
Ping @amareshsm

**Comment by snitin315** [comment]
@amareshsm Are you still working on it?

**Comment by amareshsm** [comment]
> @amareshsm Are you still working on it?

PR is ready for review.

**Review by nzakas — APPROVED** [review]
LGTM. Would like @snitin315 to take a look before merging.

**Review by snitin315 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
