### PR TITLE
style: auto complete of playground editor

### PR DESCRIPTION
**Pull request by kecrily**
| Before | After |
| - | - |
| image | image |

### CODE REVIEW

**Review by harish-sethuraman — APPROVED** [review]
LGTM

**Review by amareshsm — APPROVED** [review]

**Comment by amareshsm** [comment]
LGTM

**Comment by snitin315** [comment]
I feel the commit type should be `style`/`fix`  instead of since it is fixing stylistic issues and not a performance issue.

**Review by snitin315 — APPROVED** [review]
Looks Good!

**Comment by kecrily** [comment]
I usually use `perf` for improved PR, not just for performance improvements. And `style` I generally use for code style changes. But this may be more suitable for `style`.

**Pull request merged**
