### PR TITLE
chore: remove duplicate style properties

### PR DESCRIPTION
**Pull request by amareshsm**
**Description:** Remove duplicate style properties.

### CODE REVIEW

**Review by nzakas — COMMENTED** [review]
As I noted in the PR on the eslint repo, these duplications are intentional so we can support browsers that have CSS variables as well as those that do not.

**Comment by kecrily** [comment]
Consider that ESLint and its website are geared towards front-end developers. At the same time, according to caniuse data, all evergreen browsers already support CSS variables[^1]. I don't think there is a need for compatibility. Compatibility never ends.

[^1]: [CSS Environment  Variables env()](https://caniuse.com/?search=css%20variable)

**Comment by nzakas** [comment]
It’s true that compatibility never ends, however, good quality software aims to reach the largest audience possible. Having fallback styles allows us to do that.

We went through the trouble to do this when we built the site, so I don’t see a good argument to remove it.

**Comment by nzakas** [comment]
Since we already have the duplicate properties for backwards compatibility, let's leave them. We don't need to add any more, though.

**Pull request closed without merging**
