### PR TITLE
feat: Update install command and font.

### LINKED ISSUE #281: Playground Font
Is the font we're using considered suitable for coding? I personally find it very difficult to read code samples in this font, and round parentheses () next to each other are especially distracting as they look like a circle.

image

### PR DESCRIPTION
**Pull request by nzakas**
This uses Consolas to override the `@`, `{`, `}`, `(`, and `)` glyphs in Space Mono because they look kind of weird.

I also updated the install command on the homepage and disabled font ligatures in code examples.

Why Consolas? I tried a bunch of different fonts and this was the only one where the weight of the characters looked similar to Space Mono and didn't alter the vertical spacing too much.

This affects:

- The installation command on the homepage
- Code examples in blog posts
- Playground

This does not affect documentation. We will have to make a similar change in the eslint repo for that.

Fixes #281
Closes #254

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]
LGTM. You might need to rebase to fix the netlify build.

> This does not affect documentation. We will have to make a similar change in the eslint repo for that.

Let me know if you want help to backport this change to docs.

**Comment by kecrily** [comment]
Flickers appear on initial load and on playground input. They first become Space Mono and then Consolas.

**Comment by snitin315** [comment]
Does this happen again when you close the tab and revisit the website in a new tab?

**Comment by kecrily** [comment]
Yes, it can be steadily reproduced.
动画

**Comment by nzakas** [comment]
I think we can probably fix this by prefetching the font file. I’ll look into that.

**Comment by nzakas** [comment]
Okay, I think this fixes the problem. I'm not seeing it locally, but please verify on the deploy preview.

And thanks @kecrily for catching this!

**Comment by snitin315** [comment]
Looks like something went wrong during the rebase, there are a lot of changes now.

**Comment by nzakas** [comment]
Hmm, yes it did. Very strange. I'll take a look.

**Comment by nzakas** [comment]
Okay, got it straightened out.

**Pull request merged**
