### PR TITLE
chore: Update es.yml

### PR DESCRIPTION
**Pull request by iamabhijeet2003**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Update translations.

#### What changes did you make? (Give an overview)
chore: Update translations. English ---> Spanish
#### Related Issues
Don't Apply.

### CODE REVIEW

**Review by harish-sethuraman — APPROVED** [review]
LGTM. Thanks!

**Comment by harish-sethuraman** [comment]
Can you ammend your previous commit in the correct format?

**Comment by iamabhijeet2003** [comment]
> Can you ammend your previous commit in the correct format?

- [x] Formatted correctly the commit!

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
