### PR TITLE
chore: remove old playground's package.json and use main site's one

### PR DESCRIPTION
**Pull request by harish-sethuraman**
~I tried to run the repo and it didnt start since I didn't notice we had two package.json. It would be better to have one package.json ideally.~

preview:
Screenshot 2022-09-07 at 5 47 50 PM

Adding a fallback message that shows up before react app mounts to inform user to run `install:playground` command

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
This is intentional. We have two package.json so that the playground is built and deployed with the latest version of ESLlint available. 

See [developer setup](https://github.com/eslint/eslint.org#developer-setup), it mentions running `npm run install:playground`.

**Comment by harish-sethuraman** [comment]
How about we use one common ESLint in the whole repo and it would be latest? Just wondering why we’d need two package.json

**Comment by snitin315** [comment]
Using "latest" is problematic because we will end up getting lint errors on CI if a release introduces a breaking change.

**Comment by snitin315** [comment]
One solution is to add a `postinstall` script to run `npm run install:playground`, see [related discussion here](https://github.com/eslint/eslint.org/pull/268#discussion_r923970396).

**Comment by harish-sethuraman** [comment]
Added postinstall and it works fine

**Comment by nzakas** [comment]
We had already discussed and I’m not a fan of postinstall for this purpose. There’s no reason to go through the long playground build process unless you want to work on the playground.

**Comment by snitin315** [comment]
> We may also want to add an error message in playground.html that explains to run install:playground ( https://github.com/eslint/eslint.org/pull/268#discussion_r925066449 )

I feel this is what we need to add here.

**Comment by harish-sethuraman** [comment]
> There’s no reason to go through the long playground build process unless you want to work on the playground.

Just wondering? We are just installing two deps in playground and aren't running any build? 

> We may also want to add an error message in playground.html that explains to run install:playground ( https://github.com/eslint/eslint.org/pull/268#discussion_r925066449 )
>I feel this is what we need to add here.

Should we detect if deps (eslint) is present or not and then remove the error message shown?

**Comment by nzakas** [comment]
I don’t think we need to do any detection. Just include a static message in the playground.html file that will be overwritten if the React app loads.

**Review by harish-sethuraman — COMMENTED** [review]
Changed to show prompt to install dependencies...

**Review by amareshsm — APPROVED** [review]
LGTM

**Review by nzakas — APPROVED** [review]
Nice!

**Comment by nzakas** [comment]
@snitin315 can you please review this so we can merge?

**Review by snitin315 — APPROVED** [review]
LGTM

**Pull request merged**
