### PR TITLE
perf: memoize the extensions in code editor to reduce expensive calculations

### PR DESCRIPTION
**Pull request by shanpriyan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Memoize the extensions in code editor to reduce expensive calculations on every re-render

#### What changes did you make? (Give an overview)

Used `useMemo` to wrap the extensions array to keep the reference.

#### Is there anything you'd like reviewers to focus on?

image

Ref: https://www.npmjs.com/package/@uiw/react-codemirror?activeTab=readme

### CODE REVIEW

**Review by amareshsm — APPROVED** [review]
LGTM. I am ok with change. Leaving this open for others to verify/review.

**Review by kecrily — APPROVED** [review]
LGTM

**Comment by harish-sethuraman** [comment]
Seems to work for me? 🤔 @kecrily

**Comment by kecrily** [comment]
After some investigation I think this is a problem with the preview component of netlify

---

[Open the preview page](https://deploy-preview-441--new-eslint.netlify.app/play/), I found an error message at the bottom

image


Open the console, I found that the error report came from under netlify.com.

image

I have also tested locally and everything works fine locally.

---

@harish-sethuraman Can you verify if my research is correct?

**Comment by harish-sethuraman** [comment]
These errors do not look like its coming from our app? Its coming from netlify's deploy preview menu in the bottom I guess?

**Comment by kecrily** [comment]
> These errors do not look like its coming from our app? Its coming from netlify's deploy preview menu in the bottom I guess?

Yes, that's what I thought. Just wanted to make sure.

**Review by kecrily — APPROVED** [review]
LGTM

**Pull request merged**
