### PR TITLE
fix: no-js bugs

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What changes did you make? (Give an overview)
When javascript is disabled and the prefers-color-scheme is dark 
    1. code block texts are not visible.
    2. Logos /tag text not inverted based on the theme.

| Before  | After |
| ------------- | ------------- |
| ESLint Logo image |  image |
| Code block text color image | image |
| GitHub logo image |  image |

### CODE REVIEW

**Review by harish-sethuraman — COMMENTED** [review]
There are some places where I found css missing: 
- `/blog`
Screenshot 2022-12-14 at 1 08 28 AM

- I'd suggest we put some message in the playground page for users to enable JavaScript. Currently it looks very blank by disabling JavaScript

**Comment by amareshsm** [comment]
> There are some places where I found css missing:
> 
> * `/blog`
> 
> Screenshot 2022-12-14 at 1 08 28 AM
> 
> * I'd suggest we put some message in the playground page for users to enable JavaScript. Currently it looks very blank by disabling JavaScript

Sure. let me check and fix these things.

**Comment by kecrily** [comment]
<https://eslint.org/blog/>

<table>
  <tr>
    <th>JS</th>
    <th>No-JS</th>
  </tr>

  <tr>
    <td>
image
</td>
    <td>
截屏2022-12-17 00 35 09
</td>
  </tr>
</table>

**Comment by amareshsm** [comment]
closing this for now.

**Pull request closed without merging**
